-- ============================================================================
-- Migration 020: Fix retirement_date to September 30 — deferred no-op
-- ============================================================================
--
-- Original intent:
--   Change personnel.retirement_date to September 30 of the retirement year.
--
-- Why this is currently a no-op:
--   The original migration dropped and recreated personnel.retirement_date
--   after migrations 013/016 had already created views depending on that
--   column. A fresh `supabase db reset` therefore fails on view dependencies.
--
-- Follow-up:
--   Reintroduce this change in a future migration that drops/recreates the
--   dependent views around the generated-column change. Until then, keep the
--   functional existing formula from earlier migrations.
-- ============================================================================

-- Intentionally empty.
